version: '3.8'

services:
  clean-archcat:
    container_name: clean-archcat-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: archcatpostgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: archcat
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: clean-archcat-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
