version: '3.8'

services:
  clean-archcat:
    container_name: clean-archcat-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: archcatpostgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: archcat
    volumes:
      - ./data/pg:/data/postgres
